FlightManager/FlightManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("flights.urls")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),

]

FlightManager/flights/urls.py
from django.urls import path
from . import views

app_name = "flight"

urlpatterns = [
    path("", views.index, name="index"),
    path("book/<int:pk>", views.book, name="book"),
    path("see_flights", views.seeflights, name="seeflights"),
    path("login", views.login, name="login"),
    path("checkout", views.checkout, name="checkout"),
    path("flightdata", views.flightdata, name="flightdata"),
    path("reserve", views.reserve, name="reserve"),
    path("secret", views.createUserRecord, name="createUserRecord")

]

FlightManager/flights/models.py
from django.db import models
from django.utils import timezone
import hashlib
import random
from argon2 import PasswordHasher

class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=200)
    email = models.EmailField()
    f_name = models.CharField(max_length=20)
    l_name = models.CharField(max_length=20)
    EGN = models.CharField(max_length=12)
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=12)
    role = models.CharField(max_length=10, default="staff")

    def __str__(self):
        return f"{self.pk} - {self.username} - {self.f_name} {self.l_name} - {self.role}"



class Flight(models.Model):
    from_location = models.CharField(max_length=20)
    to_location = models.CharField(max_length=20)
    takeoff_time = models.DateTimeField()
    landing_time = models.DateTimeField()
    plane_type = models.CharField(max_length=20)
    plane_id = models.CharField(max_length=20)
    pilot_name = models.CharField(max_length=40)
    normal_ticket_count = models.IntegerField()
    business_ticket_count = models.IntegerField()
    normal_ticket_price = models.DecimalField(decimal_places=2, max_digits=5)
    business_ticket_price = models.DecimalField(decimal_places=2, max_digits=5)

    def __str__(self):
        return f"{self.pk} - {self.from_location} -> {self.to_location} - {self.plane_id}"
    
class Reservation(models.Model):
    f_name = models.CharField(max_length=20)
    m_name = models.CharField(max_length=20)
    l_name = models.CharField(max_length=20)
    EGN = models.CharField(max_length=12)
    email = models.EmailField()
    phone_number = models.CharField(max_length=12)
    nationality = models.CharField(max_length=2)
    ticket_type = models.CharField(max_length=8)
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE)

class SessionData(models.Model):
    id = models.CharField(primary_key=True, max_length=40, default=hashlib.sha1(str(random.random()).encode()).hexdigest()) #GUID
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created = models.DateTimeField(default=timezone.now, editable=False)

    def isValid(self):
        difference = timezone.now - self.created
        maxdifference = timezone.timedelta(minutes=30)

        return maxdifference >= difference

FlightManager/flights/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.forms.models import model_to_dict
from . import models
import json
from argon2 import PasswordHasher #Most secure hashing algo
import smtplib
from email.mime.multipart import MIMEMultipart 
from email.mime.text import MIMEText


ph = PasswordHasher()

def index(request):
    return render(request, "flights/index.html")

def book(request, pk):
    flight = get_object_or_404(models.Flight, pk = pk)
    ctx = {
        "data": flight
    }
    return render(request, "flights/book.html", ctx)

def seeflights(request):
    data = get_list_or_404(models.Flight)
    ctx = {
        "data": data
    }
    return render(request, "flights/seeflights.html", ctx)

def login(request):
    if request.method == "GET":
        return render(request, "flights/login.html")
    else:
        return HttpResponseRedirect("/admin")
        #data = json.loads(request.POST.get("order"))

        # username = request.POST["username"]
        # password = request.POST["password"]

        # #TODO: Handle hashing and logging in
        # dbrecord = get_object_or_404(models.User, username=username)

        # hashedpassword = getattr(dbrecord, "password")
        # try:
        #    a = ph.verify(hashedpassword, password)
        #    if a:
        #         print("Pass correct!")
        #         session = models.SessionData(user = dbrecord)
        #         request.session["user"] = session
        #         return HttpResponseRedirect("/admin") #TODO: Create staff panel
                

        # except:
        #    # print("Pass wrong! Expected - got: " + str(hashedpassword), str(ph.hash(password)))
        #     return HttpResponseRedirect("/admin") #TODO: Make this better




        # return HttpResponse("OK")


def checkout(request):
    return render(request, "flights/checkout.html")

def flightdata(request):
    pk = request.GET.get("pk", None)
    flight = get_object_or_404(models.Flight, pk= pk)
    return HttpResponse(serializers.serialize("json", [flight, ]))

def reserve(request):
    order = str(request.POST.get('order'))
    print("Order: " + order)
    try:
        data = json.loads(order)
    except json.decoder.JSONDecodeError as e:
        return HttpResponse(200)


    flight = get_object_or_404(models.Flight, pk=data[0].get("flight"))

    for item in data:        
        res_object = models.Reservation(
            f_name= item.get("f_name"),
            m_name= item.get("m_name"),
            l_name= item.get("l_name"),
            EGN= item.get("EGN"),
            email= item.get("email"),
            phone_number= item.get("phone_number"),
            nationality= item.get("nationality"),
            ticket_type= item.get("ticket_type"),
            flight= flight,
        )
        res_object.save()
        send_email(model_to_dict(res_object))
        #print(res_object)
        
    
    return HttpResponse(200)

def createUserRecord(request):
    username = input("Username: ")
    password = ph.hash(input("Password: "))
    email = input("Email: ")
    f_name = input("First name: ")
    l_name = input("Last name: ")
    EGN = input("EGN/SSN: ")
    address = input("Address: ")
    phone_number = input("Phone number: ")

    record = models.User( username= username, password = password, email = email, f_name = f_name,l_name = l_name, EGN =  EGN, address = address, phone_number = phone_number)
    record.save()
    return HttpResponse(200)
#TODO: Normal staff view using the login

def send_email(data):
    msg = MIMEMultipart()
    msg['From'] = 'mshkodrov3@gmail.com'
    msg['To'] = data["email"]
    msg['Subject'] = 'Confirmation for booking on flight ' + str(data["flight"])
    message = f"""
    Dear Sir or Madam,
    You are receiving this email to confirm your booking with Spas Airlines.
    Booking info:

    First Name: {data["f_name"]}
    Middle Name: {data["m_name"]}
    Last Name: {data["l_name"]}
    EGN: {data["EGN"]}
    Nationality: {data["nationality"]}
    ticket_type: {data["ticket_type"]}

    If the information is not correct, please contact us at contact@spasairlines.bg!


    Thank you for choosing us!
    """
    msg.attach(MIMEText(message))

    mailserver = smtplib.SMTP('smtp.gmail.com',587)
    # identify ourselves to smtp gmail client
    mailserver.ehlo()
    # secure our email with tls encryption
    mailserver.starttls()
    # re-identify ourselves as an encrypted connection
    mailserver.ehlo()
    mailserver.login('mshkodrov3@gmail.com', 'gwimuxaworzrihve')

    mailserver.sendmail('mshkodrov3@gmail.com', data["email"], msg.as_string())

    mailserver.quit()

FlightManager/flights/templates/flights/book.html
{% extends 'master.html' %}
{% block title %}
Book flight {{ data.pk }}
{% endblock title %}

{% block content %}

{% block scripts %}

<script>
    let person_num = 1;
    let regs = [];
    
    $("#title").text(`Person ${person_num}`);
    $(document).ready(function(){
        $("#end_form").toggle();
        $("#reg_form").submit(function(event){

            event.preventDefault();
            event.stopPropagation();
            
            const reg = {
                f_name: $("#f_name_field").val(),
                m_name: $("#m_name_field").val(),
                l_name: $("#l_name_field").val(),
                EGN: $("#egn_field").val(),
                email: $("#email_address_field").val(),
                phone_number: $("#phone_number_field").val(),
                nationality: $("#nationality_field").val().toUpperCase(),
                ticket_type: $("#ticket_type_field").val(),
                flight: {{ data.pk }}
            }

            regs.push(reg);
            //console.table(reg);
            $("#reg_form").toggle();
            $("#end_form").toggle();
           //$("#reg_form")[0].reset();
            $("#persons_list").append(`Person ${person_num} - ${reg.f_name} ${reg.l_name} - ${reg.EGN}<br>`);
            person_num += 1;
        });
        $("#add_person_btn").on("click", function(event){
            $("#end_form").toggle();
            $("#reg_form").toggle();
        });
        $("#checkout_btn").on("click", function(event){
            stringified =  JSON.stringify(regs);
            Cookies.set("order", stringified);
            window.location.replace("{% url 'flight:checkout' %}");          
        });
    });

    //TODO: Sum up price and add payment to total order, save reservations to model
</script>
{% endblock scripts %}
<div id="persons_list">
</div>

<div id="end_form"><h1 >Add another person?</h1><button id="add_person_btn" class="btn btn-primary">Add</button><br>
<h1>Continue to checkout?</h1><button id="checkout_btn" class="btn btn-primary">Checkout</button>
</div>

<form id="reg_form">
    <div class="form-group">
      <label for="f_name">First name:</label>
      <input type="Name" class="form-control" id="f_name_field" placeholder="Enter First Name" required>
    </div>
    <div class="form-group">
        <label for="m_name">Middle name:</label>
        <input type="Name" class="form-control" id="m_name_field" placeholder="Enter Middle Name" required>
    </div>
    <div class="form-group">
        <label for="l_name">Last name:</label>
        <input type="Name" class="form-control" id="l_name_field" placeholder="Enter Last Name" required>
    </div>
    <div class="form-group">
        <label for="EGN">EGN/SSN:</label>
        <input type="Name" class="form-control" id="egn_field" placeholder="Enter EGN/SSN" maxlength="12" required>
        <small id="egnHelp" class="form-text text-muted">Unique personal identifier between 9 and 12 characters</small>
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="email_address_field" aria-describedby="emailHelp" placeholder="Enter Email Address" required>
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="EGN">Phone Number:</label>
        <input type="text" class="form-control" id="phone_number_field" placeholder="Enter Phone Number without country code" maxlength="12" required>
    </div>
    <div class="form-group">
        <label for="nationality">Nationality</label>
        <input type="text" class="form-control" id="nationality_field" placeholder="Enter 2-letter country code" maxlength="2" required>
        <small id="emailHelp" class="form-text text-muted">Use Alpha-2 country codes as defined here: <a href="https://www.iban.com/country-codes">https://www.iban.com/country-codes</a> </small>
    </div>
    <div class="form-group">
        <label for="ticket_type">Ticket Type:</label><br>
        <select id="ticket_type_field" Name="Ticket Type" Size="2" reqired>
            <option value="normal" default> Normal </option>  
            <option value="business"> Business </option> 
        </select>
    </div>
    <div class="form-group">
        <label for="flight_id">Flight ID</label>
        <input type="number" class="form-control" id="flight_id_field" maxlength="12" placeholder="{{data.pk}}" disabled="true" required><br>
    </div>
        <button type="submit" class="btn btn-primary" id="submit_button">Submit</button>
    </form>
  <br>

{% include 'footer.html' %}
{% endblock content %}

FlightManager/flights/templates/flights/checkout.html
{% extends 'master.html' %}

{% block title %}
Checkout
{% endblock title %}

{% block content %}
{% csrf_token %}
{% block scripts %}
<script>
    var flight_data = {spas:"mirishe"};
    let total_cost = 0;

    $(document).ready(function(event){
       $.ajaxSetup({async: false});


        order = JSON.parse(Cookies.get("order"));
        let flight_id = order[0].flight;
        
        $.get(`{% url 'flight:flightdata' %}?pk=${flight_id}`, function(data){
            
        });
        $.ajax({
            type: "GET",
            url: `{% url 'flight:flightdata' %}?pk=${flight_id}`,
            success: function(data){
                let parsedData = JSON.parse(data);
                flight_data = parsedData[0].fields;
            },
            dataType: "text"
        });
        console.log(flight_data);
        
        for([index, reservation] of order.entries()){
            price = reservation.ticket_type === "normal" ? flight_data.normal_ticket_price : flight_data.business_ticket_price 
            string = `<tr><td>${index}</td><td>${reservation.f_name}</td><td>${reservation.m_name}</td><td>${reservation.l_name}</td><td>${reservation.EGN}</td><td>${flight_data.takeoff_time.slice(0, 10)}</td><td>${reservation.ticket_type}</td><td>${price}</td></tr>`
            $("#t_body").append(string);
            total_cost += Number(price);
        }
        
        let total_cost_row = `<tr><td colspan="7" align="right"><span class="label pull-right" style="padding-left:2em; padding-right:4em;">Total price:</span></td><td>${total_cost}</td></tr>`
        $("#t_body").append(total_cost_row);
        let pay_button_row = `<tr><td colspan="8" align="right"><button id="pay_btn" class="btn btn-primary pull-right" style="padding-left:2em; padding-right:2em;">Pay</button></td></tr>`;
        $("#t_body").append(pay_button_row);
        
        $("#pay_btn").one('click', function (event){
            console.log("Button Pressed")
            console.log(Cookies.get('csrftoken'));
            $.ajax({
                type: "POST",
                url: "{% url 'flight:reserve' %}",
                data: {order: JSON.stringify(order)},
                headers: {"X-CSRFToken": Cookies.get('csrftoken')},
                success: function(){
                    alert("Payment Successful!\nRedirecting!")
                },
                dataType: "text"
            });
            event.stopImmediatePropagation();
            window.location.replace("{% url 'flight:index' %}");
        });
    });
</script>
{% endblock scripts %}
<h1>Order Summary</h1>
<div id="orders">
    <table id="orders_table" class="display table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Reservation Number</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>EGN</th>
                <th>Date</th>
                <th>Ticket Type</th>
                <th>Price</th>
            </tr>
        </thead>
    <tbody id="t_body">
        <!--JS fills here-->
    </tbody>
    </table>
</div>



{% include 'footer.html' %}
{% endblock content %}

FlightManager/flights/templates/flights/index.html
{% extends 'master.html' %}

{% block title %}
Index page
{% endblock title %}
{% load static %}


{% block content %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
<style>
  .hero{
    font-family: 'Comic Neue', cursive;
  }
  .card{
    color: white;
  }
</style>

<section class="hero">
    <div class="container">
      <div class="row">
        <div class="col-md-8" style="background-image: url('{% static 'img/plane.jpg' %}'); background-position: center center;width:1300px;height:350px">
          <h1>Find Your Perfect Flight</h1>
          <form>
            <div class="form-row">
              <div class="col-md-6 form-group">
                <label for="from">From</label>
                <input type="text" class="form-control" id="from" placeholder="Departure Airport">
              </div>
              <div class="col-md-6 form-group">
                <label for="to">To</label>
                <input type="text" class="form-control" id="to" placeholder="Destination Airport">
              </div>
            </div>
            <div class="form-row">
              <div class="col-md-6 form-group">
                <label for="depart">Departure Date</label>
                <input type="date" class="form-control" id="depart">
              </div>
              <div class="col-md-6 form-group">
                <label for="return">Return Date</label>
                <input type="date" class="form-control" id="return">
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Search Flights</button>
          </form>
        </div>
      </div>
    </div>
  </section>
</header>
<main>
  <section class="services">
    <div class="container">
      <h2>Our Services</h2>
      <div class="row">
        <div class="col-md-4" >
          <div class="card" style="background-image: url('{% static 'img\Baggage_296x185.jpg' %}'); background-position: center center;width:400px;height:200px">
            
            <div class="card-body">
              <h5 class="card-title" >Baggage</h5>
              <p class="card-text" >We offer a variety of baggage options to suit your needs, including carry-on, checked, and oversized baggage.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card" style="background-image: url('{% static 'img\Food_1_296x185.jpg' %}'); background-position: center center;width:400px;height:200px">
             
            <div class="card-body">
              <h5 class="card-title">Food</h5>
              <p class="card-text">We offer a range of food and drink options on board, including snacks, meals, and beverages.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card" style="background-image: url('{% static 'img\Entertainment_296x185.jpg' %}'); background-position: center center;width:400px;height:200px">
            
            <div class="card-body">
              <h5 class="card-title">Entertainment</h5>
              <p class="card-text">We offer a variety of entertainment options on board, including movies, TV shows, and music.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="destinations">
    <div class="container">
      <h2>Popular Destinations</h2>
      <div class="row">
        <div class="col-md-4">
          <div class="card" style="background-image: url('{% static 'img\Paris_296x185.jpg' %}'); background-position: center center;width:400px;height:200px">
            
            <div class="card-body">
              <h5 class="card-title">Paris</h5>
              <p class="card-text">Experience the City of Lights with our flights to Paris. Visit the Eiffel Tower, the Louvre Museum, and more.</p>
              <a href="#" class="btn btn-primary">Book Now</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card" style="background-image: url('{% static 'img\New-York_296x185.jpg' %}'); background-position: center center;width:400px;height:200px">
            
            <div class="card-body">
              <h5 class="card-title">New York</h5>
              <p class="card-text">Fly to the Big Apple and explore all that New York City has to offer, from Central Park to Times Square.</p>
              <a href="#" class="btn btn-primary">Book Now</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card" style="background-image: url('{% static 'img\Tokyo_296x185.jpg' %}'); background-position: center center; width:400px;height:200px">
            
            <div class="card-body">
              <h5 class="card-title">Tokyo</h5>
              <p class="card-text">Discover the sights and sounds of Tokyo, from the neon-lit streets of Shinjuku to the traditional temples of Asakusa.</p>
              <a href="#" class="btn btn-primary">Book Now</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>


{% include 'footer.html' %}
{% endblock content %}

FlightManager/flights/templates/flights/login.html
{% extends 'master.html' %}

{% block title %}
Log in
{% endblock title %}
{% block content %}
{% block scripts %}
<script>
  $(document).ready(function(event){
    $.ajaxSetup({async: false});
    $("#submit_button").on('click', function (){
      data = {
        "username": $("#username").val(),
        "password": $("#password").val(),
      }

      $.ajax({
        type: "POST",
        url: "{% url 'flight:login' %}",
        data: {order: JSON.stringify(data)},
        headers: {"X-CSRFToken": Cookies.get('csrftoken')},
        success: function(){
            alert("Login Successful!\nRedirecting!");
            window.location.replace("/admin"); 
        },
        dataType: "text"
      });
    });
    
});
</script>
{% endblock scripts %}



<h1>Staff Login</h1>

<form id="reg_form">
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="Name" class="form-control" id="username" placeholder="Enter Username" required>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" id="password" placeholder="Enter Password" required>
    </div>
    <br>
    <button type="submit" class="btn btn-primary" id="submit_button">Submit</button>
</form>

{% include 'footer.html' %}
{% endblock content %}
<!--
  {"X-CSRFToken": Cookies.get('csrftoken')}
-->

FlightManager/flights/templates/flights/seeflights.html
{% extends 'master.html' %}

{% block title %}
See flights
{% endblock title %}
{% block content %}
{% block scripts %}
<script>
</script>
{% endblock scripts %}


<table id="sortTable" class="display table table table-condensed table-hover table-striped" style="width:100%; overflow-y: auto;">
    <thead>
        <tr>
            <th data-column-id="id" data-identifier="true" >Flight ID</th>
            <th data-column-id="from">From</th>
            <th data-column-id="to">To</th>
            <th data-column-id="takeoff_date">Takeoff Date</th>
            <th data-column-id="landing_date">Landing Date</th>
            <th data-column-id="plane_type">Plane Type</th>
            <th data-column-id="plane_id">Plane ID</th>
            <th data-column-id="pilot_name">Pilot Name</th>
            <th data-column-id="normal_ticket_count">Normal Ticket Count</th>
            <th data-column-id="normal_ticket_price">Normal Ticket Price</th>
            <th data-column-id="business_ticket_count">Business Ticket Count</th>
            <th data-column-id="business_ticket_price">Business Ticket Price</th>
            <th>Book</th>
        </tr>
    </thead>
    <tbody>
        {% for item in data %}
        <tr>
            <td>{{ item.pk }}</td>
            <td>{{ item.from_location }}</td>
            <td>{{ item.to_location }}</td>
            <td>{{ item.takeoff_time }}</td>
            <td>{{ item.landing_time }}</td>
            <td>{{ item.plane_type }}</td>
            <td>{{ item.plane_id }}</td>
            <td>{{ item.pilot_name }}</td>
            <td>{{ item.normal_ticket_count }}</td>
            <td>{{ item.normal_ticket_price }} BGN</td>
            <td>{{ item.business_ticket_count }}</td>
            <td>{{ item.business_ticket_price }} BGN</td>
            <td><a href="/book/{{ item.pk }}">Book Here</a>
            
        </tr>
        {% endfor %}
    </tfoot>
</table>


{% include 'footer.html' %}
{% endblock content %}

FlightManager/flights/templates/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Spas air
            </h6>
            <p>
              Founded in 1998, we have daily flights to most major hubs in Europe, and weekly flights to some of the biggest hubs in the world.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Socials
            </h6>
            <p>
              <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="text-reset">Facebook</a>
            </p>
            <p>
              <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="text-reset">Twitter</a>
            </p>
            <p>
              <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="text-reset">Instagram</a>
            </p>
            <p>
              <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="text-reset">Tiktok</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="text-reset">News</a>
            </p>
            <p>
              <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="text-reset">Cookie Policy</a>
            </p>
            <p>
              <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="text-reset">Privacy Policy</a>
            </p>
            <p>
              <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> Sofia, 1000, bul. Dondukov 2, BG</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              contact@spasair.bg
            </p>
            <p><i class="fas fa-phone me-3"></i> + 359 123 4567</p>
            <p><i class="fas fa-print me-3"></i> + 359 123 4568</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2023 Copyright:
      <a class="text-reset fw-bold" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">spasair.bg</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

FlightManager/flights/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src=" https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.min.css"/>


    <title>{% block title %}{% endblock title %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
    <div class="container-fluid" style="font-family: arial, sans-serif">
        <ul class="nav bg-info">
          <li class="nav-item">
            <a class="nav-link link-light" href="/">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'flight:seeflights' %}">See All Flights</a>
          </li>
         <!-- <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'flight:login' %}">Log In</a>
          </li>
          -->
        </ul>

        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>